# Cấu hình CSDL
spring.datasource.url=jdbc:mysql://localhost:3306/sales_management
spring.datasource.username=root
spring.datasource.password=123456789

# --- BẮT BUỘC ĐỂ CHẠY FILE DATA.SQL ---
# Ép Spring Boot luôn thực thi script SQL khởi tạo
spring.sql.init.mode=always

# Đợi Hibernate tạo/cập nhật bảng xong mới chạy data.sql
spring.jpa.defer-datasource-initialization=true
server.port=8081
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Cấu hình đường dẫn cho Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs